# ==================================================================================================================== #
# Authors:                                                                                                             #
#   Patrick Lehmann                                                                                                    #
#   Unai Martinez-Corral                                                                                               #
#                                                                                                                      #
# ==================================================================================================================== #
# Copyright 2020-2022 The pyTooling Authors                                                                            #
#                                                                                                                      #
# Licensed under the Apache License, Version 2.0 (the "License");                                                      #
# you may not use this file except in compliance with the License.                                                     #
# You may obtain a copy of the License at                                                                              #
#                                                                                                                      #
#   http://www.apache.org/licenses/LICENSE-2.0                                                                         #
#                                                                                                                      #
# Unless required by applicable law or agreed to in writing, software                                                  #
# distributed under the License is distributed on an "AS IS" BASIS,                                                    #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                             #
# See the License for the specific language governing permissions and                                                  #
# limitations under the License.                                                                                       #
#                                                                                                                      #
# SPDX-License-Identifier: Apache-2.0                                                                                  #
# ==================================================================================================================== #
name: Unit Testing

on:
  workflow_call:
    inputs:
      jobs:
        description: 'JSON list with environment fields, telling the system and Python versions to run tests with.'
        required: true
        type: string
      requirements:
        description: 'Additional python pre-requisite dependencies to be installed through pip.'
        required: false
        default: ''
        type: string
      test_command:
        description: 'Test command to run'
        required: false
        default: 'pdm run -v test -svvv -rA'
        type: string
      use_pdm:
        description: "Does this project use PDM?"
        required: false
        default: true
        type: boolean
      install_command:
        description: "Install dependencies if not using PDM"
        required: false
        default: 'pip install'
        type: string
      artifact:
        description: "Generate unit test report with junitxml and upload results as an artifact."
        required: false
        default: ''
        type: string
      run_system:
        description: 'Additional dependecies or custom system commands to run'
        required: false
        default: ''
        type: string

jobs:

  UnitTesting:
    name: ${{ matrix.sysicon }} ${{ matrix.pyicon }} Unit Tests using Python ${{ matrix.python }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.jobs) }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: ‚è¨ Checkout repository
        uses: actions/checkout@v2

      # Set up if we're not using PDM
      - name: üêç Setup Python ${{ matrix.python }}
        if: inputs.use_pdm != 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: ‚öôÔ∏è Install system dependencies
        if: inputs.run_system != ''
        run: ${{ inputs.run_system }}

      - name: ‚öôÔ∏è Update pip
        if: inputs.use_pdm != 'true'
        run: python -m pip install -U pip

      - name: üîß Install wheel and pip dependencies
        if: inputs.use_pdm != 'true'
        run: |
          python -m pip install -U wheel ${{ inputs.requirements }}

      - name: ‚öôÔ∏è Set up cache
        id: cache_not_pdm
        if: inputs.use_pdm != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ matrix.python }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: üîßInstall dependencies
        if: inputs.use_pdm != 'true' && steps.cache_not_pdm.outputs.cache-hit != 'true'
        run: |
          pipenv install --skip-lock --dev

      # Set up if we're using PDM
      - name: üêç Set up PDM
        if: inputs.use_pdm == 'true'
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python }}

      - name: ‚öôÔ∏è Set cache variables
        if: inputs.use_pdm == 'true'
        id: set_variables
        run: |
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
          echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"

      - name: ‚öôÔ∏è Set up cache
        if: inputs.use_pdm == 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.set_variables.outputs.PIP_CACHE }}
            ${{ steps.set_variables.outputs.PDM_CACHE }}
          key: tests-cache-${{ runner.os }}-${{ matrix.python }}

      - name: üîß Install dependencies
        if: inputs.use_pdm == 'true'
        run: |
          pdm use -f ${{ matrix.python }}
          pdm install -dG test

      # Run for PDM or pip
      - name: ‚òë  Run unit tests
        if: matrix.system == 'windows'
        run: |
          $PYTEST_ARGS = if ("${{ inputs.artifact }}".length -gt 0) { "--junitxml=TestReport.xml" } else { "" }
          ${{ inputs.test_command }} $PYTEST_ARGS --color=yes

      - name: ‚òë  Run unit tests
        if: matrix.system != 'windows'
        run: |
          [ 'x${{ inputs.artifact }}' != 'x' ] && PYTEST_ARGS='--junitxml=TestReport.xml' || unset PYTEST_ARGS
          ${{ inputs.test_command }} $PYTEST_ARGS --color=yes

      - name: üì§ Upload 'TestReport.xml' artifact
        if: inputs.artifact != ''
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact }}-${{ matrix.system }}-${{ matrix.python }}
          path: TestReport.xml
          if-no-files-found: error
          retention-days: 1
